In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

df=pd.read_csv("swiggy.csv")
df

ID                    Area       City                Restaurant  \
0        211             Koramangala  Bangalore               Tandoor Hut   
1        221             Koramangala  Bangalore             Tunday Kababi   
2        246               Jogupalya  Bangalore                   Kim Lee   
3        248             Indiranagar  Bangalore         New Punjabi Hotel   
4        249             Indiranagar  Bangalore                       Nh8   
...      ...                     ...        ...                       ...   
8675  464626  Panjarapole Cross Road  Ahmedabad                Malt Pizza   
8676  465835                  Rohini      Delhi  Jay Mata Ji Home Kitchen   
8677  465872                  Rohini      Delhi      Chinese Kitchen King   
8678  465990                  Rohini      Delhi    Shree Ram Paratha Wala   
8679  466488             Navrangpura  Ahmedabad              Sassy Street   

      Price  Avg ratings  Total ratings  \
0     300.0          4.4            100   
1     300.0          4.1            100   
2     650.0          4.4            100   
3     250.0          3.9            500   
4     350.0          4.0             50   
...     ...          ...            ...   
8675  500.0          2.9             80   
8676  200.0          2.9             80   
8677  150.0          2.9             80   
8678  150.0          2.9             80   
8679  250.0          2.9             80   

                                              Food type       Address  \
0             Biryani,Chinese,North Indian,South Indian     5Th Block   
1                                      Mughlai,Lucknowi     5Th Block   
2                                               Chinese   Double Road   
3                  North Indian,Punjabi,Tandoor,Chinese  80 Feet Road   
4     Rajasthani,Gujarati,North Indian,Snacks,Desser...  80 Feet Road   
...                                                 ...           ...   
8675                                             Pizzas   Navrangpura   
8676                                       South Indian        Rohini   
8677                             Chinese,Snacks,Tandoor        Rohini   
8678                         North Indian,Indian,Snacks        Rohini   
8679                               Chaat,Snacks,Chinese   Navrangpura   

      Delivery time  
0                59  
1                56  
2                50  
3                57  
4                63  
...             ...  
8675             40  
8676             28  
8677             58  
8678             28  
8679             44  

[8680 rows x 10 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             8680 non-null   int64  
 1   Area           8680 non-null   object 
 2   City           8680 non-null   object 
 3   Restaurant     8680 non-null   object 
 4   Price          8680 non-null   float64
 5   Avg ratings    8680 non-null   float64
 6   Total ratings  8680 non-null   int64  
 7   Food type      8680 non-null   object 
 8   Address        8680 non-null   object 
 9   Delivery time  8680 non-null   int64  
dtypes: float64(2), int64(3), object(5)
memory usage: 678.3+ KB


In [25]:
df.describe()

ID        Price  Avg ratings  Total ratings  Delivery time
count    8680.000000  8680.000000  8680.000000    8680.000000    8680.000000
mean   244812.071429   348.444470     3.655104     156.634793      53.967051
std    158671.617188   230.940074     0.647629     391.448014      14.292335
min       211.000000     0.000000     2.000000      20.000000      20.000000
25%     72664.000000   200.000000     2.900000      50.000000      44.000000
50%    283442.000000   300.000000     3.900000      80.000000      53.000000
75%    393425.250000   400.000000     4.200000     100.000000      64.000000
max    466928.000000  2500.000000     5.000000   10000.000000     109.000000

In [26]:
df.columns

Index(['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg ratings',
       'Total ratings', 'Food type', 'Address', 'Delivery time'],
      dtype='object')

In [27]:
df['High ratings']=(df['Avg ratings']>=4).astype(int)

X=df[['Delivery time']]
y=df['High ratings']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 1, 0], shape=(1736,))

In [28]:
test=pd.DataFrame([{'Delivery time':190}])
model.predict(test)

array([0])

In [29]:
test=pd.DataFrame([{'Delivery time':190}])
if model.predict(test) ==1:
    print("High RAte")

else:
    print("NO high rate")

NO high rate


In [30]:
#  FILE CODE
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load Dataset 
df=pd.read_csv("swiggy.csv")
df

ID                    Area       City                Restaurant  \
0        211             Koramangala  Bangalore               Tandoor Hut   
1        221             Koramangala  Bangalore             Tunday Kababi   
2        246               Jogupalya  Bangalore                   Kim Lee   
3        248             Indiranagar  Bangalore         New Punjabi Hotel   
4        249             Indiranagar  Bangalore                       Nh8   
...      ...                     ...        ...                       ...   
8675  464626  Panjarapole Cross Road  Ahmedabad                Malt Pizza   
8676  465835                  Rohini      Delhi  Jay Mata Ji Home Kitchen   
8677  465872                  Rohini      Delhi      Chinese Kitchen King   
8678  465990                  Rohini      Delhi    Shree Ram Paratha Wala   
8679  466488             Navrangpura  Ahmedabad              Sassy Street   

      Price  Avg ratings  Total ratings  \
0     300.0          4.4            100   
1     300.0          4.1            100   
2     650.0          4.4            100   
3     250.0          3.9            500   
4     350.0          4.0             50   
...     ...          ...            ...   
8675  500.0          2.9             80   
8676  200.0          2.9             80   
8677  150.0          2.9             80   
8678  150.0          2.9             80   
8679  250.0          2.9             80   

                                              Food type       Address  \
0             Biryani,Chinese,North Indian,South Indian     5Th Block   
1                                      Mughlai,Lucknowi     5Th Block   
2                                               Chinese   Double Road   
3                  North Indian,Punjabi,Tandoor,Chinese  80 Feet Road   
4     Rajasthani,Gujarati,North Indian,Snacks,Desser...  80 Feet Road   
...                                                 ...           ...   
8675                                             Pizzas   Navrangpura   
8676                                       South Indian        Rohini   
8677                             Chinese,Snacks,Tandoor        Rohini   
8678                         North Indian,Indian,Snacks        Rohini   
8679                               Chaat,Snacks,Chinese   Navrangpura   

      Delivery time  
0                59  
1                56  
2                50  
3                57  
4                63  
...             ...  
8675             40  
8676             28  
8677             58  
8678             28  
8679             44  

[8680 rows x 10 columns]

In [31]:
df.head()

ID         Area       City         Restaurant  Price  Avg ratings  \
0  211  Koramangala  Bangalore        Tandoor Hut  300.0          4.4   
1  221  Koramangala  Bangalore      Tunday Kababi  300.0          4.1   
2  246    Jogupalya  Bangalore            Kim Lee  650.0          4.4   
3  248  Indiranagar  Bangalore  New Punjabi Hotel  250.0          3.9   
4  249  Indiranagar  Bangalore                Nh8  350.0          4.0   

   Total ratings                                          Food type  \
0            100          Biryani,Chinese,North Indian,South Indian   
1            100                                   Mughlai,Lucknowi   
2            100                                            Chinese   
3            500               North Indian,Punjabi,Tandoor,Chinese   
4             50  Rajasthani,Gujarati,North Indian,Snacks,Desser...   

        Address  Delivery time  
0     5Th Block             59  
1     5Th Block             56  
2   Double Road             50  
3  80 Feet Road             57  
4  80 Feet Road             63

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             8680 non-null   int64  
 1   Area           8680 non-null   object 
 2   City           8680 non-null   object 
 3   Restaurant     8680 non-null   object 
 4   Price          8680 non-null   float64
 5   Avg ratings    8680 non-null   float64
 6   Total ratings  8680 non-null   int64  
 7   Food type      8680 non-null   object 
 8   Address        8680 non-null   object 
 9   Delivery time  8680 non-null   int64  
dtypes: float64(2), int64(3), object(5)
memory usage: 678.3+ KB


In [33]:
df.describe()

ID        Price  Avg ratings  Total ratings  Delivery time
count    8680.000000  8680.000000  8680.000000    8680.000000    8680.000000
mean   244812.071429   348.444470     3.655104     156.634793      53.967051
std    158671.617188   230.940074     0.647629     391.448014      14.292335
min       211.000000     0.000000     2.000000      20.000000      20.000000
25%     72664.000000   200.000000     2.900000      50.000000      44.000000
50%    283442.000000   300.000000     3.900000      80.000000      53.000000
75%    393425.250000   400.000000     4.200000     100.000000      64.000000
max    466928.000000  2500.000000     5.000000   10000.000000     109.000000

In [34]:
df.columns

Index(['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg ratings',
       'Total ratings', 'Food type', 'Address', 'Delivery time'],
      dtype='object')

In [35]:
"""
# Convert rating into binary output (0 or 1) 
df['High ratings']=(df['Avg ratings']>=4)
print(df['High ratings'])
"""

"\n# Convert rating into binary output (0 or 1) \ndf['High ratings']=(df['Avg ratings']>=4)\nprint(df['High ratings'])\n"

In [36]:
# Convert rating into binary output (0 or 1) 
df['High ratings']=(df['Avg ratings']>=4).astype(int)
print(df['High ratings'])

0       1
1       1
2       1
3       0
4       1
       ..
8675    0
8676    0
8677    0
8678    0
8679    0
Name: High ratings, Length: 8680, dtype: int64


In [37]:
# Input features (X) and Output (y)
# Using simple numeric columns so students can understand easily
X=df[['Price','Total ratings','Delivery time']]
y=df['High ratings']


In [38]:
# Split data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [39]:
# Create Model
model=LogisticRegression()


In [40]:
# Train model
model.fit(X_train,y_train)

LogisticRegression()

In [41]:
# Predict Probabilities
probabilities=model.predict_proba(X_test)[:,1]

In [42]:
# Convert probabilities into classes (0 or 1)
predicted_class=(probabilities>0.5).astype(int)

In [43]:
# Print outputs
print("First 10 probabilities:\n", probabilities[:10])
print("First 10 predicted classes:\n", predicted_class[:10])
print("First 10 actual classes:\n", y_test.values[:10])


First 10 probabilities:
 [0.3270105  0.35504712 0.49799004 0.54835086 0.6244189  0.25874155
 0.85209649 0.45749724 0.30572888 0.37672199]
First 10 predicted classes:
 [0 0 0 1 1 0 1 0 0 0]
First 10 actual classes:
 [1 0 1 1 1 1 1 1 1 1]


In [44]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.5455069124423964
